package Test_Cases;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;

class Simple{
	
	
	public static  void test()
	{
		System.out.println("inside test");
	}
	public static  void test1()
	{
		System.out.println("inside test");
	}
	
	
	
}  

class Dry_Run_Script{  

  
	  public static void main(String args[]) throws Exception
	  {  
		
int i = 0;
	for(;;) {
		System.out.println(i++);
	}


	 }
}  